#!/usr/bin/env python

import os
import traceback
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "mepo.d"))

from init import init
from clone import clone
from status import status
from checkout import checkout
from branch import branch
from diff import diff
from where import where
from cmdline.parser import MepoParser

if __name__ == '__main__':

    args = MepoParser().parse()
    d = {
        'init': init,
        'clone': clone,
        'status': status,
        'checkout': checkout,
        'branch': branch,
        'diff': diff,
        'where': where,
    }

    try:
        d[args.mepo_cmd].run(args)
    except Exception as e:
        traceback.print_exc()
