#!/usr/bin/env python

# importing cmdline.parser
# need a little extra work since the dirname contains dot
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "mepo.d"))
from cmdline.mepo_parser import MepoParser
from checkout import checkout
from status import status
from branch import branch

if __name__ == '__main__':

    args = MepoParser().parse()
    print args

    if args.mepo_cmd == 'checkout':
        checkout.run()

    elif args.mepo_cmd == 'status':
        status.run()

    elif args.mepo_cmd == 'branch':
        branch.run(args.mepo_branch_cmd)
