name: Unit testing of mepo

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.x, pypy-3.8]

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pyyaml build twine
        pip install -r requirements.txt
      timeout-minutes: 2
    - name: Build mepo
      run: |
        python -m build
      timeout-minutes: 2
    - name: Install mepo
      run: |
        python -m pip install .
      timeout-minutes: 2
    - name: Run unit tests
      run: |
        python3 mepo/utest/test_mepo_commands.py -v
      timeout-minutes: 2
