name: Run linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint code
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          version: "latest"

    - name: Install Python and other dependencies
      run: uv sync

    - name: Run pylint
      run: |
        source .venv/bin/activate
        pylint --exit-zero src/mepo
      timeout-minutes: 5
