name: Run linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint code
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install rye
      uses: eifinger/setup-rye@v4

    - name: Sync dependencies
      run: rye sync

    - name: Run pylint
      run: |
        source .venv/bin/activate
        pylint --exit-zero src/mepo
      timeout-minutes: 5
